// This file is autogenerated by scripts/generate-image-map.mjs

import img0 from '$lib/assets/images/about/portrait.jpg?w=400;800;1600&format=avif;webp;jpg&as=picture';
import img1 from '$lib/assets/images/about/signature.png?w=400;800;1600&format=avif;webp;jpg&as=picture';
import img2 from '$lib/assets/images/contact/square.jpg?w=400;800;1600&format=avif;webp;jpg&as=picture';
import img3 from '$lib/assets/images/home/bottom.jpg?w=400;800;1600&format=avif;webp;jpg&as=picture';
import img4 from '$lib/assets/images/home/main.jpg?w=400;800;1600&format=avif;webp;jpg&as=picture';
import img5 from '$lib/assets/images/home/portrait1.jpg?w=400;800;1600&format=avif;webp;jpg&as=picture';
import img6 from '$lib/assets/images/home/portrait2.jpg?w=400;800;1600&format=avif;webp;jpg&as=picture';
import img7 from '$lib/assets/images/logo.png?w=400;800;1600&format=avif;webp;jpg&as=picture';

export const imageMap: Record<string, any> = {
  '/src/lib/assets/images/about/portrait.jpg': img0,
  '/src/lib/assets/images/about/signature.png': img1,
  '/src/lib/assets/images/contact/square.jpg': img2,
  '/src/lib/assets/images/home/bottom.jpg': img3,
  '/src/lib/assets/images/home/main.jpg': img4,
  '/src/lib/assets/images/home/portrait1.jpg': img5,
  '/src/lib/assets/images/home/portrait2.jpg': img6,
  '/src/lib/assets/images/logo.png': img7,
};
